name: "CI"
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run test
        id: test
        run: |
          cd ./example
          nix build -L --override-input process-compose-flake ..
